### ISSUE TITLE
Server version (older than 1.17.0) is below the minimum version required (1.22.0)

### ISSUE THREAD

**Issue by oderyn** [bachya/aiolinkding#202]
**Describe the bug**

I have version 1.22.1 installed, yet I am getting this error:

```
Traceback (most recent call last):
  File "/home/user/scripts/eval/linkding/test_asyncio.py", line 17, in <module>
    asyncio.run(main())
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/scripts/eval/linkding/test_asyncio.py", line 8, in main
    client = await async_get_client("http://192.168.148.227:9090/", "add885297de131a2a0f277686a5d091b45a4eaa1")
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/aiolinkding/client.py", line 132, in async_get_client
    raise InvalidServerVersionError(
aiolinkding.errors.InvalidServerVersionError: Server version (older than 1.17.0) is below the minimum version required (1.22.0)
```

**To Reproduce**
I am running test script: 

```
#!/home/rick/.pyenv/shims/python
import asyncio

from aiolinkding import async_get_client

async def main():
    # Initialize the aiolinkding client
    client = await async_get_client("http://1912.169.148.75:8083/", "myAPICode")
    
    # Fetch bookmarks associated with a specific tag and limit the result to 1
    bookmarks_with_desired_tag = await client.bookmarks.async_get_all(query="#mytag", limit=1)
    
    # Print the result
    print(bookmarks_with_desired_tag)

# Run the async function
asyncio.run(main())
```

**Comment by bachya** [comment]
I cannot reproduce this. I have linkding 1.22.1 installed and when I run this simple script (off of the latest `dev` and with [2023.10.0](https://github.com/bachya/aiolinkding/releases/tag/2023.10.0)):

```python
"""Run a base example."""
import asyncio
import logging

from aiohttp import ClientSession

from aiolinkding import async_get_client
from aiolinkding.errors import LinkDingError

_LOGGER = logging.getLogger()

URL = "REDACTED"
TOKEN = "REDACTED"


async def main() -> None:
    """Create the aiohttp session and run the example."""
    logging.basicConfig(level=logging.INFO)
    async with ClientSession() as session:
        try:
            client = await async_get_client(URL, TOKEN, session=session)

            single_bookmark = await client.bookmarks.async_get_single(1)
            _LOGGER.info("Bookmark ID: %s", single_bookmark)
        except LinkDingError as err:
            _LOGGER.error("There was an error: %s", err)


asyncio.run(main())
```

...I get the expected result:

```sh
python examples/test_client.py
INFO:root:Bookmark ID: {'id': 1, 'url': 'https://xenitab.github.io/blog/2022/02/23/12factor/', 'title': 'Twelve-factor app anno 2022', 'description': 'The Twelve-factor app methodology turns 10. This blog posts re-evaluates  the original factors against a decade of experience with  software-as-a-service development and the maturing of serverless  development.', 'notes': '', 'website_title': None, 'website_description': None, 'is_archived': True, 'unread': False, 'shared': False, 'tag_names': ['software-development'], 'date_added': '2022-05-12T18:09:13Z', 'date_modified': '2022-07-25T17:36:29.563563Z'}
```

How are you using this library? Directly from a cloned version of the repo or downloaded via `pip`?

**Comment by oderyn** [comment]
I finally got back around to this. I started over using your examples and it is now working. Thanks for the help!
